### PR TITLE
Accessibility check

### PR DESCRIPTION
**Pull request by Geoelycom**
This pull request contains the Accessibility check done to see if my code follows web accessibility principles.
Project Analysis Report.
1. made changes to the meta-tag. (https://github.com/Geoelycom/M-portfolio/blob/43d7c572bb6cdcc161851a0d3ce7aafdc664119c/index.html#L5)
2. Add a description. (https://github.com/Geoelycom/M-portfolio/blob/43d7c572bb6cdcc161851a0d3ce7aafdc664119c/index.html#L6)
3. Add a title to the website. -(https://github.com/Geoelycom/M-portfolio/blob/43d7c572bb6cdcc161851a0d3ce7aafdc664119c/index.html#L9)
4. Add Keywords for search engine optimization- (https://github.com/Geoelycom/M-portfolio/blob/43d7c572bb6cdcc161851a0d3ce7aafdc664119c/index.html#L7l)
5. Made sure all images are resizable- "no issues found"
6. checked for image text alternatives - "no issues found"
7.  Interactions - "no issues found".
8. Headings - "no issues found".
9. Text headings- "no issues found"
10. multimedia - "no issues found"
11. Basic structure of the page - "no issues found"

### CODE REVIEW

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

_This is a brilliant effort from you guys. You've really done an amazing job so far._

- Your PR looks professional with a nice title and summary :heavy_check_mark: 
- Linter checks are running with no errors :+1: 

__However, you need to make some required changes before moving on to the next assignment.__
> Keep in mind that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it :blush: 
----
### **Required Changes** :recycle: 

- [x] Please note that for each of the points listed in your evaluation, you need to ensure that if you need to change something, you need to add the link to the corresponding line of code in your Pull Request changes (evaluation). 
Although you specified some lines in your evaluation, you did not do it the right way. Kindly check the gif image below to better understand how to add the link of such lines.
permlink

- [x] Your page is having a horizontal scroll bar on desktop screen sizes. The full width of your page should be visible without having to scroll to either left or right. This is a resizing issue. Kindly find a way to eliminate the horizontal scroll bar.
- [x] Kindly update the live demo link on your Readme: the recent changes seem to be missing in the current one.
- [x] You mentioned that there are no issues found when you checked for color contrast. However, I checked the color contrast of your portfolio with [this aditus tool](https://www.aditus.io/button-contrast-checker/) and I found a couple of issues. Kindly use the same tool to identify the issues and fix them as appropriate.

### **Optional Changes** :zap: 
N/A

* * *
**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@teekaytech) so I can be notified about your comments and respond._

*REMINDER: As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).*

_**Please make the required changes and submit another review request when you are done.**_

* * *

_Reviewed by:_ [**Taofeek Olalere**](https://github.com/teekaytech)
__Cheers & Happy coding :smiley:__

**Comment by Geoelycom** [comment]
hello, looking at the GIf in this comment you have used to review this PR isn't mine but that of Simon. how do I go about this now?  there's no way I'm going to be making changes to my code without knowing what I'm looking for? please take a look at this. I will go ahead and add the link to the evaluations.

**Comment by Geoelycom** [comment]
Commenting on changes requested for the Demo link, I can't update it because the PR hasn't been approved and I haven't merged it into master, once it's merged it will automatically update. As the Link to the Demo link is the link to my Github pages. if there's a way I can do it, I'm open to suggestions.

changing the color or the contrast of the three buttons and the Brand (logo)would result in me not using the specifics provided in the project description, as suggested I'm to follow the design of the template chosen as much possible as I can. I have gone ahead to remove that evaluation to avoid any conflicts. if there is a way I can do it while also staying in line with project requirements, I would love it if you can point me in this direction.

**Comment by Geoelycom** [comment]
In the meantime, I have gone ahead to submit this PR for another review.

**Review by smcommits — APPROVED** [review]
### Status: Approved 👍🏽 

Hi @Geoelycom, 

## You have done a great job! Your project is complete. This PR is now approved. You can go ahead and merge the branch. Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by teekaytech** [comment]
> Commenting on changes requested for the Demo link, I can't update it because the PR hasn't been approved and I haven't merged it into master, once it's merged it will automatically update. As the Link to the Demo link is the link to my Github pages. if there's a way I can do it, I'm open to suggestions.
> 
> changing the color or the contrast of the three buttons and the Brand (logo)would result in me not using the specifics provided in the project description, as suggested I'm to follow the design of the template chosen as much possible as I can. I have gone ahead to remove that evaluation to avoid any conflicts. if there is a way I can do it while also staying in line with project requirements, I would love it if you can point me in this direction.

Hello, @smcommits,
Thank you for your comments, it always feels good to have this kind of interaction :blush: 

Apologies for replying a bit late, it was nighttime in my time zone.

I get your point about the demo link. One way of solving this problem is to use [githack](http://rawcdn.githack.com/) to provide a temporary live demo link in your feature branch. Then after approval, you can change it to the GitHub Pages link. However, do not dwell too much on this, I only mentioned it so you don't forget to include it after approval.

About the Color contrast, you should try to balance things up. Yes, you should follow the design **as much as possible**, but in my opinion, if it requires you to make some little changes to have a good color contrast, I don't think it's a bad idea. 

Congratulations on getting the project approved :handshake:

**Pull request merged**
